name: Update Data

on:
  schedule:
    - cron:  '0 2 * * *'
    - cron:  '0 4 * * *'
    - cron:  '0 6 * * *'
  workflow_dispatch:
    inputs:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Update data
        run: cd rki-scrape && npm ci && npm run update
      - name: Status
        run: git status
      - uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'Update COVID data'
          add: 'rki-scrape/data/*.json'
